<?php
// classes/ReportExporter.php - CSV export writer
//
// Uses EnrollmentReport for data.
// No direct DB access here — all data comes from EnrollmentReport.

require_once 'EnrollmentReport.php';
require_once 'Enrollment.php';

class ReportExporter {
    private $report;
    private $enrollment;

    public function __construct() {
        $this->report     = new EnrollmentReport();
        $this->enrollment = new Enrollment();
    }

    /**
     * Export full analysis report to CSV.
     */
    public function exportAnalysisReport() {
        $filename = 'enrollment_analysis_report_' . date('Y-m-d_His') . '.csv';
        $this->setHeaders($filename);

        $output = fopen('php://output', 'w');
        fprintf($output, chr(0xEF) . chr(0xBB) . chr(0xBF)); // UTF-8 BOM

        $data = $this->report->getFullReport();

        $this->writeHeader($output, $data);
        $this->writeSummary($output, $data['summary']);
        $this->writeEnrollmentByCourse($output, $data['enrollment_by_course']);
        $this->writeEnrollmentByYear($output, $data['enrollment_by_year']);
        $this->writeEnrollmentBySection($output, $data['enrollment_by_section']);
        $this->writeMonthlyTrend($output, $data['monthly_trend']);
        $this->writePredictive($output, $data['predictive'], $data['summary']);
        $this->writeStudents($output, $data['students']);
        $this->writePendingApplications($output, $data['pending_applications']);
        $this->writeIncompleteRequirements($output, $data['incomplete_requirements']);
        $this->writeRecentEnrollments($output, $data['recent_enrollments']);

        $archivedStudents = $this->enrollment->getArchivedStudents();
        $this->writeArchivedStudents($output, $archivedStudents);

        fputcsv($output, ['']);
        fputcsv($output, ['']);
        fputcsv($output, ['=== END OF REPORT ===']);
        fputcsv($output, ['Generated by Bestlink College Enrollment System']);

        fclose($output);
        exit;
    }

    /**
     * Export student list only.
     */
    public function exportStudentList() {
        $filename = 'student_list_' . date('Y-m-d_His') . '.csv';
        $this->setHeaders($filename);

        $output = fopen('php://output', 'w');
        fprintf($output, chr(0xEF) . chr(0xBB) . chr(0xBF));

        fputcsv($output, ['STUDENT LIST REPORT']);
        fputcsv($output, ['Generated:', date('l, F d, Y h:i A')]);
        fputcsv($output, ['Generated By:', $_SESSION['user_name'] ?? 'System']);
        fputcsv($output, ['']);

        $this->writeStudents($output, $this->report->getAllStudentsWithDetails());

        fclose($output);
        exit;
    }

    /**
     * Export summary only.
     */
    public function exportSummary() {
        $filename = 'enrollment_summary_' . date('Y-m-d_His') . '.csv';
        $this->setHeaders($filename);

        $output = fopen('php://output', 'w');
        fprintf($output, chr(0xEF) . chr(0xBB) . chr(0xBF));

        $data = $this->report->getFullReport();

        $this->writeHeader($output, $data);
        $this->writeSummary($output, $data['summary']);
        $this->writeEnrollmentByCourse($output, $data['enrollment_by_course']);
        $this->writeEnrollmentByYear($output, $data['enrollment_by_year']);

        fclose($output);
        exit;
    }

    /**
     * Export archive report to CSV.
     */
    public function exportArchiveReport() {
        $filename = 'archived_students_report_' . date('Y-m-d_His') . '.csv';
        $this->setHeaders($filename);

        $output = fopen('php://output', 'w');
        fprintf($output, chr(0xEF) . chr(0xBB) . chr(0xBF));

        fputcsv($output, ['ARCHIVED STUDENTS REPORT']);
        fputcsv($output, ['Generated:', date('l, F d, Y h:i A')]);
        fputcsv($output, ['Generated By:', $_SESSION['user_name'] ?? 'System']);
        fputcsv($output, ['']);
        fputcsv($output, ['']);

        $archivedStudents = $this->enrollment->getArchivedStudents();

        $reasonCounts = [
            'Dropped'     => 0,
            'Transferred' => 0,
            'LOA'         => 0,
            'Graduated'   => 0,
            'Other'       => 0
        ];

        foreach ($archivedStudents as $s) {
            $reason = $s['archive_reason'] ?? 'Other';
            if (isset($reasonCounts[$reason])) {
                $reasonCounts[$reason]++;
            } else {
                $reasonCounts['Other']++;
            }
        }

        fputcsv($output, ['=== SUMMARY ===']);
        fputcsv($output, ['Metric', 'Value']);
        fputcsv($output, ['Total Archived Students', count($archivedStudents)]);
        fputcsv($output, ['']);
        fputcsv($output, ['Breakdown by Reason:', '']);
        fputcsv($output, ['Dropped', $reasonCounts['Dropped']]);
        fputcsv($output, ['Transferred', $reasonCounts['Transferred']]);
        fputcsv($output, ['Leave of Absence (LOA)', $reasonCounts['LOA']]);
        fputcsv($output, ['Graduated', $reasonCounts['Graduated']]);
        fputcsv($output, ['Other', $reasonCounts['Other']]);
        fputcsv($output, ['']);
        fputcsv($output, ['']);
        fputcsv($output, ['=== ARCHIVED STUDENTS LIST ===']);
        fputcsv($output, [
            'Student #', 'Full Name', 'Email', 'Contact',
            'Course', 'Section', 'Year Level', 'Admission Type',
            'Reason', 'Archived At', 'Archived By'
        ]);

        foreach ($archivedStudents as $s) {
            $fullName = trim(
                ($s['first_name'] ?? '') . ' ' .
                ($s['middle_name'] ?? '') . ' ' .
                ($s['surname'] ?? '') . ' ' .
                ($s['suffix'] ?? '')
            );

            $archivedAt = !empty($s['archived_at'])
                ? date('M d, Y h:i A', strtotime($s['archived_at']))
                : 'N/A';

            $archivedBy = $s['archived_by_name']
                ?? $s['archived_by_username']
                ?? 'System';

            $yearLevel = $s['grade_level']
                ?? (isset($s['year_level']) ? $s['year_level'] . 'th Year' : 'N/A');

            fputcsv($output, [
                $s['student_number']   ?? 'N/A',
                $fullName,
                $s['email']            ?? 'N/A',
                $s['contact_number']   ?? 'N/A',
                $s['course_code']      ?? 'N/A',
                $s['section_code']     ?? 'Not Assigned',
                $yearLevel,
                ucfirst($s['admission_type'] ?? 'N/A'),
                $s['archive_reason']   ?? 'N/A',
                $archivedAt,
                $archivedBy
            ]);
        }

        fputcsv($output, ['']);
        fputcsv($output, ['']);
        fputcsv($output, ['=== END OF REPORT ===']);
        fputcsv($output, ['Generated by Bestlink College Enrollment System']);

        fclose($output);
        exit;
    }

    /* ============================================================
       PRIVATE WRITER METHODS
    ============================================================ */

    private function setHeaders($filename) {
        header('Content-Type: text/csv; charset=utf-8');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Pragma: no-cache');
        header('Expires: 0');
    }

    private function writeHeader($output, $data) {
        fputcsv($output, ['ENROLLMENT ANALYSIS REPORT']);
        fputcsv($output, ['Generated:', $data['generated_at'] ?? '']);
        fputcsv($output, ['Generated By:', $data['generated_by'] ?? 'System']);
        fputcsv($output, ['']);
        fputcsv($output, ['']);
    }

    private function writeSummary($output, $summary) {
        fputcsv($output, ['=== SUMMARY STATISTICS ===']);
        fputcsv($output, ['Metric', 'Value']);

        $labels = [
            'total_students'           => 'Total Students',
            'active_students'          => 'Active Students',
            'total_enrollments'        => 'Total Subject Enrollments',
            'total_applications'       => 'Total Applications',
            'pending_applications'     => 'Pending Applications',
            'converted_applications'   => 'Converted Applications',
            'rejected_applications'    => 'Rejected Applications',
            'total_sections'           => 'Total Sections',
            'total_courses'            => 'Total Courses',
            'conversion_rate'          => 'Conversion Rate (%)'
        ];

        foreach ($labels as $key => $label) {
            fputcsv($output, [$label, $summary[$key] ?? 0]);
        }

        try {
            $archivedCount = $this->enrollment->getArchivedStudentCount();
            fputcsv($output, ['Archived Students', $archivedCount]);
        } catch (Exception $e) {
            fputcsv($output, ['Archived Students', 0]);
        }

        fputcsv($output, ['']);
        fputcsv($output, ['']);
    }

    private function writeEnrollmentByCourse($output, $courses) {
        fputcsv($output, ['=== ENROLLMENT BY COURSE ===']);
        fputcsv($output, ['Course Code', 'Course Name', 'Students', 'Subject Enrollments']);

        foreach ($courses as $c) {
            fputcsv($output, [
                $c['course_code']   ?? 'N/A',
                $c['course_name']   ?? 'N/A',
                $c['student_count'] ?? 0,
                $c['subject_count'] ?? 0
            ]);
        }

        fputcsv($output, ['']);
        fputcsv($output, ['']);
    }

    private function writeEnrollmentByYear($output, $years) {
        fputcsv($output, ['=== ENROLLMENT BY YEAR LEVEL ===']);
        fputcsv($output, ['Year Level', 'Students', 'Subject Enrollments']);

        foreach ($years as $y) {
            fputcsv($output, [
                $y['grade_level']   ?? 'N/A',
                $y['student_count'] ?? 0,
                $y['subject_count'] ?? 0
            ]);
        }

        fputcsv($output, ['']);
        fputcsv($output, ['']);
    }

    private function writeEnrollmentBySection($output, $sections) {
        fputcsv($output, ['=== ENROLLMENT BY SECTION ===']);
        fputcsv($output, ['Section Code', 'Course', 'Year Level', 'Semester', 'Students', 'Subject Enrollments']);

        foreach ($sections as $s) {
            fputcsv($output, [
                $s['section_code']  ?? 'N/A',
                $s['course_code']   ?? 'N/A',
                $s['grade_level']   ?? 'N/A',
                $s['semester']      ?? 'N/A',
                $s['student_count'] ?? 0,
                $s['subject_count'] ?? 0
            ]);
        }

        fputcsv($output, ['']);
        fputcsv($output, ['']);
    }

    private function writeMonthlyTrend($output, $trend) {
        fputcsv($output, ['=== MONTHLY TREND (' . date('Y') . ') ===']);
        fputcsv($output, ['Month', 'Enrollments', 'Applications']);

        foreach ($trend as $row) {
            fputcsv($output, [
                $row['month']        ?? 'N/A',
                $row['enrollments']  ?? 0,
                $row['applications'] ?? 0
            ]);
        }

        fputcsv($output, ['']);
        fputcsv($output, ['']);
    }

    private function writePredictive($output, $predictive, $summary) {
        fputcsv($output, ['=== PREDICTIVE ANALYTICS ===']);
        fputcsv($output, ['Metric', 'Value']);
        fputcsv($output, ['Average Monthly Growth', ($predictive['avg_growth'] ?? 0) . '%']);
        fputcsv($output, ['Predicted Next Month Enrollments', $predictive['predicted_next_month'] ?? 0]);
        fputcsv($output, ['Predicted Next Quarter Enrollments', $predictive['predicted_next_quarter'] ?? 0]);
        fputcsv($output, ['Current Conversion Rate', ($summary['conversion_rate'] ?? 0) . '%']);

        fputcsv($output, ['']);
        fputcsv($output, ['']);
    }

    private function writeStudents($output, $students) {
        fputcsv($output, ['=== STUDENTS LIST ===']);
        fputcsv($output, [
            'Student #', 'Name', 'Course', 'Section', 'Year Level',
            'Type', 'Status', 'Email', 'Contact', 'Enrolled Date'
        ]);

        foreach ($students as $s) {
            $fullName = trim(
                ($s['first_name'] ?? '') . ' ' .
                ($s['middle_name'] ?? '') . ' ' .
                ($s['surname'] ?? '') . ' ' .
                ($s['suffix'] ?? '')
            );

            fputcsv($output, [
                $s['student_number']     ?? 'N/A',
                $fullName,
                $s['course_code']        ?? 'N/A',
                $s['section_code']       ?? 'N/A',
                $s['year_level']         ?? 'N/A',
                ucfirst($s['admission_type'] ?? 'N/A'),
                ucfirst($s['enrollment_status'] ?? 'N/A'),
                $s['email']              ?? 'N/A',
                $s['contact_number']     ?? 'N/A',
                $s['enrolled_at']        ?? 'N/A'
            ]);
        }

        fputcsv($output, ['']);
        fputcsv($output, ['']);
    }

    private function writePendingApplications($output, $apps) {
        fputcsv($output, ['=== PENDING APPLICATIONS ===']);
        fputcsv($output, ['ID', 'Name', 'Course', 'Email', 'Contact', 'Type', 'Submitted']);

        foreach ($apps as $a) {
            $name = trim(($a['first_name'] ?? '') . ' ' . ($a['surname'] ?? ''));
            fputcsv($output, [
                $a['applicant_id']     ?? 'N/A',
                $name,
                $a['course_code']      ?? 'N/A',
                $a['email']            ?? 'N/A',
                $a['contact_number']   ?? 'N/A',
                ucfirst($a['admission_type'] ?? 'N/A'),
                $a['submitted_at']     ?? 'N/A'
            ]);
        }

        fputcsv($output, ['']);
        fputcsv($output, ['']);
    }

    private function writeIncompleteRequirements($output, $students) {
        fputcsv($output, ['=== STUDENTS WITH INCOMPLETE REQUIREMENTS ===']);
        fputcsv($output, ['Student #', 'Name', 'Course', 'Submitted', 'Total', 'Completion %']);

        foreach ($students as $s) {
            $name      = trim(($s['first_name'] ?? '') . ' ' . ($s['surname'] ?? ''));
            $submitted = (int) ($s['submitted_count'] ?? 0);
            $total     = (int) ($s['total_requirements'] ?? 0);
            $pct       = $total > 0 ? round($submitted / $total * 100, 1) : 0;

            fputcsv($output, [
                $s['student_number'] ?? 'N/A',
                $name,
                $s['course_code']    ?? 'N/A',
                $submitted,
                $total,
                $pct . '%'
            ]);
        }

        fputcsv($output, ['']);
        fputcsv($output, ['']);
    }

    private function writeRecentEnrollments($output, $enrollments) {
        fputcsv($output, ['=== RECENT ENROLLMENTS ===']);
        fputcsv($output, [
            'Student #', 'Name', 'Subject', 'Course',
            'Section', 'Schedule', 'Faculty', 'Room', 'Enrolled'
        ]);

        foreach ($enrollments as $e) {
            $name = trim(($e['first_name'] ?? '') . ' ' . ($e['surname'] ?? ''));

            $schedule = '';
            if (!empty($e['day_of_week'])) {
                $schedule = $e['day_of_week']
                    . ' ' . ($e['start_time'] ?? '')
                    . '-' . ($e['end_time'] ?? '');
            }

            $faculty = trim(
                ($e['faculty_first'] ?? '') . ' ' . ($e['faculty_last'] ?? '')
            );

            fputcsv($output, [
                $e['student_number'] ?? 'N/A',
                $name,
                $e['subject_code']   ?? 'N/A',
                $e['course_code']    ?? 'N/A',
                $e['section_code']   ?? 'N/A',
                $schedule ?: 'No schedule',
                $faculty ?: 'N/A',
                $e['room_code']      ?? 'N/A',
                $e['enrolled_at']    ?? 'N/A'
            ]);
        }

        fputcsv($output, ['']);
    }

    private function writeArchivedStudents($output, $students) {
        fputcsv($output, ['=== ARCHIVED STUDENTS ===']);
        fputcsv($output, ['Student #', 'Name', 'Course', 'Section', 'Reason', 'Archived At', 'Archived By']);

        foreach ($students as $s) {
            $fullName = trim(
                ($s['first_name'] ?? '') . ' ' .
                ($s['middle_name'] ?? '') . ' ' .
                ($s['surname'] ?? '') . ' ' .
                ($s['suffix'] ?? '')
            );

            $archivedAt = !empty($s['archived_at'])
                ? date('M d, Y', strtotime($s['archived_at']))
                : 'N/A';

            $archivedBy = $s['archived_by_name']
                ?? $s['archived_by_username']
                ?? 'System';

            fputcsv($output, [
                $s['student_number'] ?? 'N/A',
                $fullName,
                $s['course_code']    ?? 'N/A',
                $s['section_code']   ?? 'Not Assigned',
                $s['archive_reason'] ?? 'N/A',
                $archivedAt,
                $archivedBy
            ]);
        }

        fputcsv($output, ['']);
        fputcsv($output, ['']);
    }
}